Mon Dec 23 09:49:43 CET 2024
NVIDIA A100-SXM4-40GB
2024-12-23 09:49:46.871076: W external/xla/xla/service/gpu/nvptx_compiler.cc:836] The NVIDIA driver's CUDA version is 12.5 which is older than the PTX compiler version (12.6.85). Because the driver is older than the PTX compiler version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.
Warning: weights not properly specified, assuming constant weights instead.
GPU found?
[CudaDevice(id=0)]
Fixed params loaded inside the MicroToMacroTransform:
    E_sat: -16.0
Loading data necessary for the event GW170817
Loading data necessary for the event J0030 and sampling the with NICER masses
Loading data necessary for the event J0740 and sampling the with NICER masses
Not sampling PREX or CREX data now
Loading data necessary for the Chiral EFT
Sanity checking: likelihoods_list = [<paper_jose.utils.GWlikelihood_with_masses object at 0x14fcccacfb50>, <paper_jose.utils.NICERLikelihood_with_masses object at 0x14f316d69ba0>, <paper_jose.utils.NICERLikelihood_with_masses object at 0x14f316a89240>, <paper_jose.utils.RadioTimingLikelihood object at 0x14f316d39a50>, <paper_jose.utils.RadioTimingLikelihood object at 0x14fbd0c059f0>, <paper_jose.utils.RadioTimingLikelihood object at 0x14fbd0c05900>, <paper_jose.utils.ChiEFTLikelihood object at 0x14fbd0c059c0>]
len(likelihoods_list) = 7
Fixed params loaded inside the MicroToMacroTransform:
    E_sat: -16.0
We are going to give these kwargs to Jim:
{'n_loop_training': 100, 'n_loop_production': 20, 'n_chains': 500, 'n_local_steps': 2, 'n_global_steps': 100, 'n_epochs': 20, 'train_thinning': 1, 'output_thinning': 1}
We are going to sample the following parameters:
['E_sym', 'L_sym', 'K_sym', 'Q_sym', 'Z_sym', 'K_sat', 'Q_sat', 'Z_sat', 'nbreak', 'n_CSE_0_u', 'cs2_CSE_0', 'n_CSE_1_u', 'cs2_CSE_1', 'n_CSE_2_u', 'cs2_CSE_2', 'n_CSE_3_u', 'cs2_CSE_3', 'n_CSE_4_u', 'cs2_CSE_4', 'n_CSE_5_u', 'cs2_CSE_5', 'n_CSE_6_u', 'cs2_CSE_6', 'n_CSE_7_u', 'cs2_CSE_7', 'n_CSE_8_u', 'cs2_CSE_8', 'n_CSE_9_u', 'cs2_CSE_9', 'n_CSE_10_u', 'cs2_CSE_10', 'n_CSE_11_u', 'cs2_CSE_11', 'n_CSE_12_u', 'cs2_CSE_12', 'n_CSE_13_u', 'cs2_CSE_13', 'n_CSE_14_u', 'cs2_CSE_14', 'n_CSE_15_u', 'cs2_CSE_15', 'n_CSE_16_u', 'cs2_CSE_16', 'n_CSE_17_u', 'cs2_CSE_17', 'n_CSE_18_u', 'cs2_CSE_18', 'n_CSE_19_u', 'cs2_CSE_19', 'n_CSE_20_u', 'cs2_CSE_20', 'n_CSE_21_u', 'cs2_CSE_21', 'n_CSE_22_u', 'cs2_CSE_22', 'n_CSE_23_u', 'cs2_CSE_23', 'n_CSE_24_u', 'cs2_CSE_24', 'n_CSE_25_u', 'cs2_CSE_25', 'n_CSE_26_u', 'cs2_CSE_26', 'n_CSE_27_u', 'cs2_CSE_27', 'n_CSE_28_u', 'cs2_CSE_28', 'n_CSE_29_u', 'cs2_CSE_29', 'cs2_CSE_30', 'mass_1_GW170817', 'mass_2_GW170817', 'mass_J0030', 'mass_J0740']
No sample transforms provided. Using prior parameters as sampling parameters
['n_dim', 'n_chains', 'n_local_steps', 'n_global_steps', 'n_loop', 'output_thinning', 'verbose']
log_prob
[-1.00001397e+07 -5.68168128e+02 -1.12785420e+02]
Global Tuning:   0%|          | 0/100 [00:00<?, ?it/s]jax.pure_callback failed
Traceback (most recent call last):
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/callback.py", line 86, in pure_callback_impl
    return tree_util.tree_map(np.asarray, callback(*args))
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/callback.py", line 64, in __call__
    return tree_util.tree_leaves(self.callback_func(*args, **kwargs))
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/equinox/_errors.py", line 89, in raises
    raise _EquinoxRuntimeError(
equinox._errors._EquinoxRuntimeError: The maximum number of solver steps was reached. Try increasing `max_steps`.


--------------------
An error occurred during the runtime of your JAX program! Unfortunately you do not appear to be using `equinox.filter_jit` (perhaps you are using `jax.jit` instead?) and so further information about the error cannot be displayed. (Probably you are seeing a very large but uninformative error message right now.) Please wrap your program with `equinox.filter_jit`.
--------------------

E1223 09:57:16.929562 2545300 pjrt_stream_executor_client.cc:3067] Execution of replica 0 failed: INTERNAL: CustomCall failed: CpuCallback error: Traceback (most recent call last):
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/paper_jose/src/paper_jose/inference/inference.py", line 428, in <module>
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/paper_jose/src/paper_jose/inference/inference.py", line 365, in main
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/jim/src/jimgw/jim.py", line 119, in sample
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/Sampler.py", line 204, in sample
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/strategy/global_tuning.py", line 174, in __call__
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/proposal/NF_proposal.py", line 130, in sample
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/proposal/NF_proposal.py", line 198, in sample_flow
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 332, in cache_miss
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 190, in _python_pjit_helper
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/core.py", line 2739, in bind
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/core.py", line 433, in bind_with_trace
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/core.py", line 939, in process_primitive
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 1730, in _pjit_call_impl
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 1712, in call_impl_cache_miss
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 1666, in _pjit_call_impl_python
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/profiler.py", line 336, in wrapper
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 1239, in __call__
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 2656, in _wrapped_callback
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/callback.py", line 228, in _callback
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/callback.py", line 89, in pure_callback_impl
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/callback.py", line 64, in __call__
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/equinox/_errors.py", line 89, in raises
_EquinoxRuntimeError: The maximum number of solver steps was reached. Try increasing `max_steps`.


--------------------
An error occurred during the runtime of your JAX program! Unfortunately you do not appear to be using `equinox.filter_jit` (perhaps you are using `jax.jit` instead?) and so further information about the error cannot be displayed. (Probably you are seeing a very large but uninformative error message right now.) Please wrap your program with `equinox.filter_jit`.
--------------------

Global Tuning:   0%|          | 0/100 [04:50<?, ?it/s]
Compiling MALA body
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/paper_jose/src/paper_jose/inference/inference.py", line 428, in <module>
    main(args)
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/paper_jose/src/paper_jose/inference/inference.py", line 365, in main
    jim.sample(jax.random.PRNGKey(11))
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/jim/src/jimgw/jim.py", line 119, in sample
    self.sampler.sample(initial_position, None)  # type: ignore
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/Sampler.py", line 204, in sample
    ) = strategy(
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/strategy/global_tuning.py", line 174, in __call__
    ) = global_sampler.sample(
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/proposal/NF_proposal.py", line 130, in sample
    proposal_position, log_prob_proposal, log_prob_nf_proposal = self.sample_flow(
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/proposal/NF_proposal.py", line 198, in sample_flow
    self.logpdf_vmap(proposal_position[i], data)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: CustomCall failed: CpuCallback error: Traceback (most recent call last):
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/paper_jose/src/paper_jose/inference/inference.py", line 428, in <module>
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/paper_jose/src/paper_jose/inference/inference.py", line 365, in main
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/jim/src/jimgw/jim.py", line 119, in sample
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/Sampler.py", line 204, in sample
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/strategy/global_tuning.py", line 174, in __call__
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/proposal/NF_proposal.py", line 130, in sample
  File "/gpfs/home6/twouters2/projects/jax_tov_eos/flowMC/src/flowMC/proposal/NF_proposal.py", line 198, in sample_flow
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/traceback_util.py", line 180, in reraise_with_filtered_traceback
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 332, in cache_miss
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 190, in _python_pjit_helper
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/core.py", line 2739, in bind
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/core.py", line 433, in bind_with_trace
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/core.py", line 939, in process_primitive
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 1730, in _pjit_call_impl
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 1712, in call_impl_cache_miss
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/pjit.py", line 1666, in _pjit_call_impl_python
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/profiler.py", line 336, in wrapper
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/interpreters/pxla.py", line 1239, in __call__
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/interpreters/mlir.py", line 2656, in _wrapped_callback
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/callback.py", line 228, in _callback
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/callback.py", line 89, in pure_callback_impl
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/jax/_src/callback.py", line 64, in __call__
  File "/home/twouters2/miniconda3/envs/jose/lib/python3.10/site-packages/equinox/_errors.py", line 89, in raises
_EquinoxRuntimeError: The maximum number of solver steps was reached. Try increasing `max_steps`.


--------------------
An error occurred during the runtime of your JAX program! Unfortunately you do not appear to be using `equinox.filter_jit` (perhaps you are using `jax.jit` instead?) and so further information about the error cannot be displayed. (Probably you are seeing a very large but uninformative error message right now.) Please wrap your program with `equinox.filter_jit`.
--------------------




Postprocessing now
suffix
30
Note: the given suffix is a number, therefore we assume this is a CSE systematics run, so we will make all plots
Making plots for ./CSE_systematics/outdir_30/
Number of samples: 100000
Creating NS plot . . .
  0%|          | 0/3001 [00:00<?, ?it/s]  3%|▎         | 76/3001 [00:00<00:03, 757.27it/s]  5%|▌         | 153/3001 [00:00<00:03, 760.10it/s]  8%|▊         | 230/3001 [00:00<00:03, 762.91it/s] 10%|█         | 307/3001 [00:00<00:03, 765.11it/s] 13%|█▎        | 384/3001 [00:00<00:03, 764.91it/s] 15%|█▌        | 461/3001 [00:00<00:03, 638.79it/s] 18%|█▊        | 539/3001 [00:00<00:03, 677.61it/s] 21%|██        | 618/3001 [00:00<00:03, 708.00it/s] 23%|██▎       | 697/3001 [00:00<00:03, 731.10it/s] 26%|██▌       | 776/3001 [00:01<00:02, 746.72it/s] 28%|██▊       | 855/3001 [00:01<00:02, 756.71it/s] 31%|███       | 934/3001 [00:01<00:02, 765.04it/s] 34%|███▍      | 1013/3001 [00:01<00:02, 769.56it/s] 36%|███▋      | 1091/3001 [00:01<00:02, 655.42it/s] 39%|███▉      | 1170/3001 [00:01<00:02, 690.25it/s] 42%|████▏     | 1249/3001 [00:01<00:02, 715.78it/s] 44%|████▍     | 1328/3001 [00:01<00:02, 736.20it/s] 47%|████▋     | 1407/3001 [00:01<00:02, 750.17it/s] 50%|████▉     | 1486/3001 [00:02<00:01, 759.46it/s] 52%|█████▏    | 1565/3001 [00:02<00:01, 767.03it/s] 55%|█████▍    | 1644/3001 [00:02<00:01, 770.83it/s] 57%|█████▋    | 1723/3001 [00:02<00:01, 774.87it/s] 60%|██████    | 1801/3001 [00:02<00:01, 614.24it/s] 63%|██████▎   | 1880/3001 [00:02<00:01, 656.46it/s] 65%|██████▌   | 1959/3001 [00:02<00:01, 690.21it/s] 68%|██████▊   | 2038/3001 [00:02<00:01, 715.67it/s] 71%|███████   | 2117/3001 [00:02<00:01, 734.30it/s] 73%|███████▎  | 2196/3001 [00:03<00:01, 749.02it/s] 76%|███████▌  | 2275/3001 [00:03<00:00, 758.58it/s] 78%|███████▊  | 2354/3001 [00:03<00:00, 766.26it/s] 81%|████████  | 2433/3001 [00:03<00:00, 772.14it/s] 84%|████████▎ | 2512/3001 [00:03<00:00, 774.77it/s] 86%|████████▋ | 2591/3001 [00:03<00:00, 778.39it/s] 89%|████████▉ | 2670/3001 [00:03<00:00, 575.24it/s] 92%|█████████▏| 2749/3001 [00:03<00:00, 624.40it/s] 94%|█████████▍| 2828/3001 [00:03<00:00, 665.68it/s] 97%|█████████▋| 2907/3001 [00:04<00:00, 697.04it/s] 99%|█████████▉| 2984/3001 [00:04<00:00, 716.80it/s]100%|██████████| 3001/3001 [00:04<00:00, 718.45it/s]
Bad counter: 0
Creating NS plot . . . DONE
Reading Hauke data
Loading weights from /home/twouters2/hauke_eos/weights/all.txt
Weights at these bad indices
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Shape of mtov_list: (99941,)
Shape of r14_list: (99941,)
Shape of l14_list: (99941,)
Shape of ntov_list: (0,)
Shape of p3nsat_list: (99941,)
np.shape(weights)
(99941,)
Reading Hauke data DONE
Creating histograms . . .
  0%|          | 0/100000 [00:00<?, ?it/s]  4%|▍         | 3946/100000 [00:00<00:02, 39452.98it/s]  8%|▊         | 8005/100000 [00:00<00:02, 40119.99it/s] 12%|█▏        | 12018/100000 [00:00<00:02, 40050.55it/s] 16%|█▌        | 16045/100000 [00:00<00:02, 40135.51it/s] 20%|██        | 20087/100000 [00:00<00:01, 40235.31it/s] 24%|██▍       | 24133/100000 [00:00<00:01, 40310.86it/s] 28%|██▊       | 28169/100000 [00:00<00:01, 40323.76it/s] 32%|███▏      | 32220/100000 [00:00<00:01, 40381.85it/s] 36%|███▋      | 36259/100000 [00:00<00:01, 40368.07it/s] 40%|████      | 40297/100000 [00:01<00:01, 40369.12it/s] 44%|████▍     | 44334/100000 [00:01<00:01, 40337.33it/s] 48%|████▊     | 48376/100000 [00:01<00:01, 40359.84it/s] 52%|█████▏    | 52412/100000 [00:01<00:01, 40266.83it/s] 56%|█████▋    | 56439/100000 [00:01<00:01, 40260.13it/s] 60%|██████    | 60472/100000 [00:01<00:00, 40280.36it/s] 65%|██████▍   | 64501/100000 [00:01<00:00, 40247.58it/s] 69%|██████▊   | 68534/100000 [00:01<00:00, 40269.66it/s] 73%|███████▎  | 72561/100000 [00:01<00:00, 40240.43it/s] 77%|███████▋  | 76586/100000 [00:01<00:00, 40222.02it/s] 81%|████████  | 80609/100000 [00:02<00:00, 40204.85it/s] 85%|████████▍ | 84630/100000 [00:02<00:00, 40196.44it/s] 89%|████████▊ | 88657/100000 [00:02<00:00, 40217.18it/s] 93%|█████████▎| 92682/100000 [00:02<00:00, 40224.99it/s] 97%|█████████▋| 96705/100000 [00:02<00:00, 40175.23it/s]100%|██████████| 100000/100000 [00:02<00:00, 40209.05it/s]
Negative counter: 0
Mass at 2 nsat: 1.17-0.89+1.36
TOV mass: 2.53-0.53+0.68
R1.4: 13.49-1.62+1.64
n_TOV: 4.6803 - 1.7146 + 2.1687
p3nsat: 147.57-100.75+123.53
This is the all-constraints run. Therefore, we also make the master plot!
Percentage of EOS samples that are above 0.33: 99.88%



Postprocessing done
DONE

JOB STATISTICS
==============
Job ID: 9136046
Cluster: snellius
User/Group: twouters2/twouters2
State: COMPLETED (exit code 0)
Nodes: 1
Cores per node: 18
CPU Utilized: 00:09:20
CPU Efficiency: 6.30% of 02:28:12 core-walltime
Job Wall-clock time: 00:08:14
Memory Utilized: 2.53 GB
Memory Efficiency: 12.64% of 20.00 GB
